---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nautobot-helm
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/nautobot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: nautobot-helm
  interval: 1m0s
  install:
    createNamespace: true
  targetNamespace: nautobot-helm
  valuesFrom:
  - kind: ConfigMap
    name: nautobot-helm
    valuesKey: nautobot.yaml
